name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ExperssionBuilder.sln
      working-directory: ExperssionBuilder
    - name: Build
      run: dotnet build ExperssionBuilder.sln --configuration Release --no-restore
      working-directory: ExperssionBuilder
    - name: Test
      run: dotnet test ExperssionBuilder.sln --no-restore --verbosity normal
      working-directory: ExperssionBuilder
