name: Release to Nuget

on:  
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: dotnet build ExpressionBuilder.csproj -c Release -v n
      working-directory: ExperssionBuilder
    - name: Create NuGet Package
      run: dotnet pack ExpressionBuilder.csproj -c Release -v n --no-build --output 'nupkgs' /p:Version=${{ github.event.release.tag_name }} /p:PackageReleaseNotes="See https://github.com/KitsKlip/ExpressionBuilder/tags/${{ github.event.release.tag_name }}"
      working-directory: ExperssionBuilder
    - name: List all Directories
      shell: pwsh
      run: get-childitem -directory -d 3 -r 
    - name: List all Files
      shell: pwsh
      run: get-childitem -file  -d 3 -r
    - name: Archive NuGet Package
      uses: actions/upload-artifact@v1
      with:
        name: Uhuru.ExpressionBuilder        
        path: ExpressionBuilder/nupkgs/Uhuru.ExpressionBuilder.${{ github.event.release.tag_name }}.nupkg
