
name: Release to Nuget to GitHub

on:  
  push:
    branches: [ivomp-patch-1]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet build ExpressionBuilder.csproj -c Release -v n /p:Version=${{ github.event.release.tag_name }} /p:PackageReleaseNotes="See https://github.com/KitsKlip/ExpressionBuilder/tags/${{ github.event.release.tag_name }}"
      working-directory: ExperssionBuilder   
    - name: Publish Nuget Package
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGETAPIKEY }} --source "github" --no-symbols true
